const Strings = {
  en: {
    NoData: 'No Data',
    Swiper1Header: 'Immense Connections',
    Swiper1SubHeader: 'Connect to numerous patients easily',
    Swiper2Header: 'Fast Transactions',
    Swiper2SubHeader: 'Receive auto-generated transaction reports',
    Swiper3Header: 'Accurate Record Keeping',
    Swiper3SubHeader:
      'Keep track of your consultation records in a convenient way',
    Success: 'Success',
    Error: 'Error',
    CameraPermission:
      "We need to access your camera to scan patient's QR code for the verify and payment process",
    PleaseEnableCameraPermission:
      "We need camera access to provide full functionalities. Please enable camera access in your phone's setting",
    auth: {
      ST0: 'Login',
      ST1: 'Register',
      ST2: 'Email',
      LoginPassword: 'Login Password',
      ST4: 'Forget Password',
      ST5: 'Enter',
      ST6: 'Confirm',
      OperationPassword: 'Operation Password',
      ForgetPasswordEmail:
        'If your email is registered, you will receive an email containing an password reset link.',
      ForgetPassword: 'Forget Password',
      AccountPendingApproval: 'Account pending approval',
      AccountDisabled: 'Account disabled',
      AsyncStorageError: 'System error, please retry',
      IncorrectCredential: 'Incorrect login email or password',
      MissingField: 'Please enter your Email and Password',
      NetworkError: 'Network error, please check your network and retry',
      SessionExpired: 'Your session has been expired. Please login again',
    },
    tab: {
      Home: 'Home',
      Verify: 'Verify',
      Modify: 'Pay',
      Record: 'Record',
      Setting: 'Settings',
    },

    doctor_profile: {
      Title: 'Doctor profile',
      Doctor_code: 'Doctor code',
      Name_cn: 'Doctor name (Chinese)',
      Name_en: 'Doctor name (English)',
      Gender: 'Gender',
      Service_hour: 'Service hours',
      Location_code: 'Location code',
      Doctor_fee: 'Agreed medical fee',
      Insurer_name: 'Insurer name',
      Benefit_code: 'Benefit code',
      Speciality: 'Speciality',
      Authority: 'Registration authority',
      Active: 'Active',
      Inactive: 'Inactive',
    },
    register: {
      ST44: 'Password',
      ST45: 'Clinic Registration email',
      ST46: 'Name of Registrant',
      ST47: 'Telephone Number of Registrant',
      ST48: 'REST of the Bank Account Numbers',
      ST49: 'Next',
      ST50: 'Registrant Details',
      ST51: 'Please enter a valid email address',
      ST52: 'Password must be at least 6 characters long',
      ST53: 'Name cannot be empty',
      ST54: 'Please enter a valid phone number',
      ST55: 'Please enter a valid bank account number.',
      ST56: 'Clinic Name (English)',
      ST57: 'Please enter a valid clinic name',
      ST58: 'Clinic Name (Chinese)',
      ST59: '2/4: Clinic Details',
      ST60: 'Clinic Address(English)',
      ST61: 'Please enter a valid clinic address',
      ST62: 'Clinic Address(Chinese)',
      ST63: 'District',
      ST64: 'Region',
      ST65: 'Select',
      ST66: 'Please select district',
      ST67: 'Clinic Telephone Number (1)',
      ST68: 'Clinic Telephone Number (2), (optional)',
      ST69: 'Clinic Fax Number 1 (optional)',
      ST70: 'Clinic Fax Number 2 (optional)',
      ST71: 'Monday',
      ST72: 'Tuesday',
      ST73: 'Wednesday',
      ST74: 'Thursday',
      ST75: 'Friday',
      ST76: 'Saturday',
      ST77: 'Sunday',
      ST78: 'Service hours',
      ST79: 'Edit',
      ST80: 'Please choose a bank',
      InvalidInputs: 'Please fill in all the field correctly',
      BusinessCertMissing: 'Please upload business registration certificate',
      DoctorCertMissing: 'Please upload doctor practising certificate',
      BankCodeInvalid: 'Please select a bank',
      DistrictHint: 'Please select district',
      RegionHint: 'Please select Region',
      genderHint: 'Please select gender',
      insurerHint: 'Please select insurer',
      RegisterPerson: 'Register Person',
      Title: 'Registration',
      StepTwoTopic: 'Clinic Details',
      StepThreeTopic: 'Doctor Details',
      StepFourTopic: 'Confirm Details',
      BankCode: 'FIRST 3 digits of the Bank Account Number',
      BankAccountUserName: 'Bank Account Holder Name',
      PracticingCertificate: 'Certificate of Practice',
      Upload: 'Upload',
      Bank: 'Bank',
      SelectBank: 'Select bank',

      BusinessRegistrationCertificate: 'Business Registration Certificate',

      SelectRegion: 'Select Region',
      SelectDistrict: 'Select District',
      // Page 3/4
      AddDoctorAlert: 'Please add 1 or more doctors',
      DoctorNameEn: 'Doctor Name (English)',
      DoctorNameCn: 'Doctor Name (Chinese)',
      Gender: 'Gender',
      Male: 'Male',
      Female: 'Female',
      MedicalServices: 'Speciality',
      SelectMedicalService: 'Please Select Speciality',
      RegistrationAuthority: 'Registered Authority',
      InsurerOptions: 'Insurer Options',
      SelectBenefitCode: 'Select Benefit Code',
      Price: 'Agreed Medical Fee',
      DoctorList: 'Doctor List',
      SaveCurrentDoctor: 'Save current doctor',
      AddNewDoctor: 'Add new doctor',
      SelectInsurer: 'Select Insurer',
      BenefitHint: 'Please select benefit type',
      AuthorityHint: 'Please select registered authority',
      IncorrectInsurerOptions: 'Please fill in correct insurer options',

      // Page 4/4
      Hint: 'Please check and make sure the inputted information is correct',
      Edit: 'Edit',
      ConsentAlert: 'Please tick all three boxes of agreement',
      bankAccountUserNameNotValid:
        'Please enter a valid bank account user name',
      phoneOrFaxNumberNotValid: 'Please input correct phone or fax number',
      doctorNameNotValid: 'Please enter a valid doctor name',
      genderNotValid: 'Gender is not selected',
      medicalServiceNotValid: 'Speciality is invalid, please type again',
      registrationAuthorityNotValid: 'Please select a Registration Authority',
      practicingCertificateNotChoose: 'Please upload Certificate of Practice',
      insurerOptionsNotValid:
        'Insurer options are not valid, please type again',
      RegisterSuccess:
        'Account registration success. Please wait for the approval.',
      RegisterFail: 'Account registration fail. Please contact support.',
      EmailRegistered: 'Email already registered',
    },
    tick1_Text00: 'I agree to and accept the',
    tick1_Text01: 'Terms of Use',

    tick2_Text00: 'I agree to and accept the latest version of',
    tick2_Text01: 'Service Agreement with MediConCen',

    tick3_Text00: 'I have read and understand',
    tick3_Text01: 'Collection Of Personal Data',
    tick3_Text02: 'and accept the information promoted by MediConCen',
    home: {
      ST0: 'Verify',
      ST1: 'Pay',
      ST2: 'Records',
      ST3: 'Reports',
      ST4: 'Cooperators',
      ST5: 'Updates',
      ST6: 'Clinic Only',
    },
    verify: {
      ST0: 'Select Benefit',
      ST1: 'Select Doctor',
      ST2: 'Verify-Scan QR Code',
      ST3: 'Scan Again',
      ST4: 'Patient Info',
      ST5: 'Patient ID',
      ST6: 'Co-payment Amount',
      ST7: 'Extra Medicine Fee Claim Limit',
      ST8: 'Referral Letter',
      ST9: 'Eligibility',
      ST10: 'Notice',
      ST11: 'Necessary',
      ST12: 'Not Necessary',
      ST13: 'Pass',
      ST14: 'Fail',
      ST15: 'Enter Verify QR Code',
      ST16: 'Switch doctor',
      SelectBenefit: 'Verify - Select Benefit',
      SelectDoctor: 'Verify - Select Doctor',
      SelectVerifyMethod: 'Select Verify Method',
      Insurer: 'Insurance company',
      BcExample: 'Please fill in 1 + \"/\" + 2'
    },
    modify: {
      ST0: 'Payment-Scan QR Code',
      ST1: 'Select Diagnosis',
      ST2: 'Selected Diagnosis',
      ST3: 'Continue',
      Back: 'Back',
      ST4: 'Add Extra Medicine',
      ST5: 'Payment QRcode',
      ST6: 'Diagnosis',
      ST7: 'Service Type',
      ST8: 'Extra Medicine',
      ST9: '99212 - Out-patient',
      ST10: 'Name',
      ST11: 'Price',
      ST12: 'Add',
      ST13: 'Confirm Payment',
      ST14: 'Payment Info',
      ST15: 'Please collect from client',
      ST16: 'Co-payment',
      ST17: 'Extra Medicine',
      ST18: 'Collect from Network',
      ST19: 'Doctor Details',
      ST20: 'Doctor Name',
      ST21: 'Type of Consultation',
      ST22: 'Patient Details',
      ST23: 'Enter Payment QR Code',
      ST24: 'User ID',
      ST25: 'Diagnosis',
      ST26: 'Service Type',
      ST27: 'Extra Medication',
      ST28: 'Transaction Time',
      ST29: 'Claim Reference No',
      ST30: 'Search diagnosis',
      ST31: 'Patient Name',
      ST32: 'Card Type',
      ST33: 'Policy Number',
      ST34: 'Transaction Method',
      ST35: 'Total',
      ClinicPaid: 'Clinic Fee',
      ExtraMedFee: 'Patient\'s Extra Medical Fee',
      PleasePaid: 'Please Charge from Patient',
      Signature: 'Signature',
      ClearSignature: 'Clear Signature',
      SigndInvoice: 'Patient have signed invoice',
      PhysicalCard: 'Physical Card',
      SelectBenefit: 'Payment - Select Benefit',
      SelectDoctor: 'Payment - Select Doctor',
      WarnAtMostTwoDiagnosis: 'You can only select at most two diagnoses',
      InvalidExtraMedFields: 'Invalid extra medicine fields. May be invalid characters or invalid type of input values detected, including but not limited to characters * | , " : < > [ ] { } ` \' ; ( ) @ & $ # % ',
      InvalidNumberOfDiagnosis: 'invalid number of diagnosis',
      PaymentSuccess: 'Payment success',
      PaymentFail: 'Payment fail',
      ExtraMedTotal: 'Extra Medication (Total price)',
      ConfirmWarning:
        '*Once you click submit, you are not allowed to make any changes*',
      Submit: 'Submit',
      ConfirmDetails: 'Confirm Details',
      SelectVerifyMethod: 'Select Payment Verify Method',
      PatientDetail: 'Patient Information',
      NextPayment: 'Next Payment',
      TransactionComplete: 'Transaction Completed',
      DoctorName: 'Doctor Name',
      ServiceType: 'Office or other outpatient',
      Diagnosis: 'Diagnosis'
    },
    record: {
      ST0: 'Records',
      ST1: 'All',
      ST2: 'Completed',
      ST3: 'Refunded',
      ST4: 'User ID',
      ST5: 'Doctor',
      ST6: 'Claim Ref No.',
      ST7: 'Transaction time',
      ST8: 'Enter Operation Password',
      ST9: 'Operation Password',
      ST10: 'Cancel',
      ST11: 'Confirm',
      Refund: 'Refund',
      RefundSuccess: 'Refund success',
      RefundFail: 'Refund fail',
      Refunded: 'Refunded',
      RecordDetail: 'Record Details',
      NoRecord: 'No Records',
      Type: 'Type',
      RefundTime: 'Refund Time',
      PickDate: 'Pick a Date',
    },
    others: {
      ST0: 'Settings',
      ST1: 'Profile',
      ST2: 'About Us',
      ST3: 'Terms and Conditions',
      ST4: 'Privacy Policy',
      ST5: 'Rate Us',
      ST6: 'Share',
      ST7: 'Language Setting',
      ST8: 'Logout',
      ST9: 'Blockchain medical ecosystem',
      ST10: 'Service Agreement',
      ST11: 'Change Password',
      display_settings: 'Display Settings',

      Personal_profile: 'My Profile',
      Clinic_profile: 'Clinic Profile',
      Doctor_profile: 'Doctor Profile',
      PasswordReset: 'Reset password',
      OldPassword: 'Confirm old password',
      WrongOldPassword: 'Old password incorrect',
      NewPassword: 'New password',
      NewPasswordConfirm: 'Confirm new password',
      NewPasswordNotMatch: 'Your new passwords do not match',
      PasswordResetSuccess:
        'Password reset success. You have to use the new password at next login.',
    },

    Settings: {
      DisplayAmountFromNetwork: 'Display "amount collected from network"',
      saveSettings: 'Save Settings',
      saveSettingsSuccessfully: 'Save Settings Successfully',
      saveSettingsFailed: 'Failed to save settings',
    },

    logout: {
      Logout_title: 'Logout',
      Logout_content: 'Are you sure you want to logout?',
    },
    profile: {
      ST0: 'My Profile',
      ST1: 'Clinic Profile',
      ST2: 'Doctor Profile',
      ST3: 'Clinic registration email (Login)',
      ST4: 'Password',
      ST5: 'Operation password',
      ST6: 'Contact person',
      ST7: 'Contact telephone number',
      ST8: 'Bank account',
      ST9: 'Business Registration Certificate',
      ST10: 'Edit',
      ST11: 'Clinic name (English)',
      ST12: 'Clinic name (Chinese)',
      ST13: 'Clinic address (English)',
      ST14: 'Clinic address (Chinese)',
      ST15: 'District',
      ST16: 'Region',
      ST17: 'Clinic telephone number 1',
      ST18: 'Clinic telephone number 2 (Optional)',
      ST19: 'Clinic fax number',
      ST20: 'Service hours',
      ST21: 'Monday',
      ST22: 'Tuesday',
      ST23: 'Wednesday',
      ST24: 'Thursday',
      ST25: 'Friday',
      ST26: 'Saturdays',
      ST27: 'Sunday',
      ST28: 'Public Holidays',
      ST29: 'Closed',
      ST30: 'Doctor name (English)',
      ST31: 'Doctor name (Chinese)',
      ST32: 'Gender',
      ST33: 'Male',
      ST71: 'Registration number',
      ST72: 'Title of qualification',
      ST73: 'Name of issuing institution',
      ST74: 'Year of issue',
      ST75: 'Qualifications',
      ST76: 'Speciality',
      ST77: '—',
      ST78: 'Female',

      ST88: 'Select Service',
      ST89: 'Price',
      ST90: 'Proposed Medical Consultation Fee',
      ST91: 'Registrant Details',
      ST92: 'Clinic Details',
      ST93: 'Doctor Details',
      ST94: 'The Medical Council of Hong Kong',
      ST95: 'Chinese Medicine Council of Hong Kong',
      ST96: 'The Dental Council of Hong Kong ',
      ST97: 'Chiropractors Council',
      ST98: 'Physiotherapists Board',
      ST99: 'Registration Authority',
      SelectInsurer: 'Select Insurer',
    },
    authorities: {
      1: 'The Medical Council of Hong Kong',
      2: 'Chinese Medicine Council of Hong Kong',
      3: 'The Dental Council of Hong Kong',
      4: 'Chiropractors Council',
      5: 'Physiotherapists Board',
    },
    medicalServices: {
      1: 'General Practice',
      2: 'Speciality',
      3: 'Chinese Medicine',
      4: 'Physiotherapy',
      6: 'Dentistry',
      7: 'Other',
      9: 'Cardiology',
      10: 'Cardio-thoracic Surgery',
      12: 'Clinical Oncology',
      13: 'Dermatology',
      14: 'Endocrinology, Diabetes & Metabolism',
      15: 'Family Medicine',
      16: 'Gastroenterology & Hepatology',
      17: 'General Surgery',
      18: 'Haematology & Haematological Oncology',
      19: 'Internal Medicine',
      20: 'Medical Oncology',
      21: 'Nephrology',
      22: 'Neurology',
      23: 'Obstetrics',
      24: 'Ophthalmology',
      25: 'Orthopaedics & Traumatology',
      26: 'Otorhinolaryngology',
      27: 'Paediatrics',
      28: 'Plastic Surgery',
    },
    regions: {
      0: 'Select',
      1: 'Hong Kong Island',
      2: 'Kowloon',
      3: 'New Territories',
    },
    districts: {
      3: {
        3: 'Islands',
        5: 'Kwai Tsing',
        7: 'North',
        8: 'Sai Kung',
        9: 'Sha Tin',
        12: 'Tai Po',
        13: 'Tsuen Wan',
        14: 'Tuen Mun',
        17: 'Yuen Long',
      },
      2: {
        4: 'Kowloon City',
        6: 'Kwun Tong',
        10: 'Sham Shui Po',
        16: 'Wong Tai Sin',
        18: 'Yau Tsim Mong',
      },
      1: {
        1: 'Central and Western',
        2: 'Eastern',
        11: 'Southern',
        15: 'Wan Chai',
      },
    },
    benefitCode: {
      PHY:
        'General Practitioner(PHY)/Consultation fee with 3 days prescription',
      SPL:
        'Specialist Practitioner(SPL)/ Consultation fee with 3 days prescription',
      HER: 'Chinese Herbalist(HER)/Consultation fee with 2 days prescription',
      BST: 'Bonesetter(BST)/Consultation fee with single treatment session',
      ACU: 'Acupuncture(ACU)/Consultation fee with single treatment session',
      ROE: 'Dentist(ROE)/Scaling and polishing with Oral Exam',
      PHS:
        'Physiotherapy(PHS)/Single treatment session without shockwave service',
      CHI: 'Chiropractic(CHI)/Single treatment session',
      SPO:
        'Sports/Exercise therapy(SPO)/ Consultation fee with single treatment session',
    },
    insurer: {
      BlueCross: 'Blue Cross',
      Bowtie: 'Bowtie',
    },
    service_times: [
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
      'Sunday',
      'Public Holidays',
    ],

    clinic: {
      Open: 'Open',
      Closed: 'Closed',
      AddServiceHour: 'Add service hour',
    },

    report: {
      Recent_summary: 'Business Overview for last 6 months',
      Monthly_income_and_download: 'Monthly summary',
      Average_client_count: 'Average Number of Clients per day',
      Total_income: 'Income',
      Client_count: 'Number of Clients',
      Download_text: 'Download Monthly Report',
      ReportSent:
        'Report sent to your email. Please check in your mailbox/spam.',
      ReportFail:
        'System error. Could not send report to your email. Please contact support',
      Confirm_download: 'Confirm Download?',
      Income: 'Income',
      MonthlySummary: 'Monthly Summary',
    },
    scan: {
      IncorrectCodeFormat: 'Error in code format, please scan a valid code',
      InvalidCodeError:
        'This code is no available or is used, please scan a valid code',
      UnknownCodeError:
        'Unknown error occurred,please try again or contact our support',
    },
    physicalCard: {
      title: 'Please enter physical card\' information',
      card: 'Physical Card',
      policyNo: 'Please enter policy Number',
      submit: 'Submit',
      description: 'Please enter physical card\'s policy number for ',
      selected: 'selected',
      a: 'Please enter policy no',
    },

    ErrorCode: 'Error Code',
    Confirm: 'Confirm',
    Cancel: 'Cancel',
    RequestCamPermission: 'Requesting for camera permission',
    Retry: 'Retry',
    Return: 'Return',
    ST0: 'Login',
    ST1: 'Register',
    ST2: 'Email',
    ST3: 'Password',
    ST4: 'Forget Password',
    ST5: 'Enter',
    ST6: 'Confirm',

    ST7: 'Verify',
    ST8: 'Pay',
    ST9: 'Records',
    ST10: 'Reports',
    ST11: 'Cooperators',
    ST12: 'Updates',
    ST13: 'Select Benefit',
    ST14: 'Select Doctor',
    ST15: 'Verify-Scan QR Code',
    ST16: 'Scan Again',
    ST17: 'User Details',
    ST18: 'User ID',
    ST19: 'Co-payment Amount',
    ST20: 'Extra Medicine Fee Claim Limit',
    ST21: 'Referral Letter',
    ST22: 'Eligibility',
    ST23: 'Cautions',
    ST24: 'Necessary',
    ST25: 'Not Necessary',
    ST26: 'Pass',
    ST27: 'Fail',

    ST28: 'Payment-Scan QR Code',
    ST29: '1/2 - Diagnosis Confirm',
    ST30: 'Selected Diagnosis (At most 2)',
    ST31: 'Continue',
    ST32: '2/2 - Diagnosis Confirm',
    ST33: 'Payment QR Code',
    ST34: 'Diagnosis',
    ST35: 'Service Type',
    ST36: 'Extra Medication',
    ST37: '99212 - OFFICE OR OTHER OUTPATIENT VISIT FOR THE EVALUATION',
    ST38: 'Name',
    ST39: 'Price',
    ST40: 'Add',
    ST41: 'Confirm Payment',
    ST42: 'Payment Info',
    ST43: 'Please collect from client',
    ST44: 'Co-payment',
    ST45: 'Extra medication',
    ST46: 'Collect from network',
    ST47: 'Doctor Details',
    ST48: 'Doctor Name (Code)',
    ST49: 'Type of Consultation',
    ST50: 'Patient Details',
    ST51: '',
    ST52: 'Promotion Details',
    ST53: 'Update',
    ST54: 'QR Code',
    ST55: 'Physical Card',
    IncorrectOPPassword: 'Incorrect operation password',
    Next: 'Next',
    Save: 'Save',

    Close: 'Close',

    UnknownSystemError: 'Unknown system error occurs. Please try again or contact support.',
    trust_parter: 'OUR TRUSTED PARTNERS',
  },

  chi: {
    NoData: '無數據',
    Swiper1Header: '龐大連結',
    Swiper1SubHeader: '輕鬆聯繫龐大醫療用戶',
    Swiper2Header: '實時交易',
    Swiper2SubHeader: '取得自動產生交易報告',
    Swiper3Header: '準確紀錄',
    Swiper3SubHeader: '方便保留您的診症紀錄',
    Success: '成功',
    Error: '錯誤',
    CameraPermission:
      '我們需要使用你的相機掃描病人的 QR code，以執行驗證及付費功能',
    PleaseEnableCameraPermission:
      '我們需要存取相機權限以提供所有功能，請在手機的設定中允許醫結診所App使用相機',
    auth: {
      ST0: '登入',
      ST1: '註冊',
      ST2: '電郵',
      LoginPassword: '系統登錄密碼',
      ST4: '忘記密碼',
      ST5: '輸入',
      ST6: '確認',
      OperationPassword: '操作密碼',
      ForgetPasswordEmail:
        '如果你的電郵地址已註冊，你將會收到一封電郵讓你重置密碼',
      ForgetPassword: '忘記密碼',
      AccountPendingApproval: '帳號正在等待批核',
      AccountDisabled: '帳號已停用',
      AsyncStorageError: '系統錯誤，請重試',
      IncorrectCredential: '登入電郵或密碼錯誤',
      MissingField: '請輸入電郵及密碼',
      NetworkError: '網絡錯誤，請檢查你的網絡並重試',
      SessionExpired: '你的登錄時段已失效，請重新登入',
    },
    back: '返回',

    register: {
      ST44: '密碼',
      ST45: '診所的電郵地址',
      ST46: '註冊人姓名',
      ST47: '註冊人聯絡電話號碼',
      ST48: '銀行卡賬戶餘下數字',
      ST49: '下一步',
      ST50: '登記人資料',
      ST51: '請輸入正確的電郵格式',
      ST52: '密碼長度最少為六',
      ST53: '名字不能填空',
      ST54: '聯絡電話格式錯誤',
      ST55: '請輸入正確的銀行戶口',
      ST56: '診所英文名稱',
      ST57: '請輸入正確的診所名稱',
      ST58: '診所中文名稱',
      ST59: '2/4: 診所資料',
      ST60: '診所英文地址',
      ST61: '請輸入正確的診所地址',
      ST62: '診所中文地址',
      ST63: '地區',
      ST64: '區域',
      ST65: '請選擇',
      ST66: '請選擇地區',
      ST67: '診所電話號碼（1）',
      ST68: '診所電話號碼（2），選填',
      ST69: '診所傳真號碼（選填）',
      ST70: '診所傳真號碼（2）,選填',
      ST71: '星期一',
      ST72: '星期二',
      ST73: '星期三',
      ST74: '星期四',
      ST75: '星期五',
      ST76: '星期六',
      ST77: '星期日',
      ST78: '開放時間',
      ST79: '編輯',
      ST80: '請選擇銀行',
      RegisterPerson: '登記人資料',
      Title: '註冊',
      StepTwoTopic: '診所資料',
      StepThreeTopic: '醫生資料',
      StepFourTopic: '確認資料',
      BankCode: '銀行卡賬戶頭三位數字',
      BankAccountUserName: '銀行賬戶持有人名稱',
      PracticingCertificate: '執業證書',
      Upload: '上傳',
      Bank: '銀行',
      SelectBank: '選擇銀行',
      InvalidInputs: '請檢查並確保所有輸入正確',
      BusinessCertMissing: '請上傳商業登記證',
      DoctorCertMissing: '請上傳醫生執業證書',
      BankCodeInvalid: '請選擇銀行',
      DistrictHint: '請選擇地區',
      RegionHint: '請選擇區域',
      genderHint: '請選擇性別',
      insurerHint: '請選擇保險公司',
      BusinessRegistrationCertificate: '商業登記証',

      SelectRegion: '請選擇區域',
      SelectDistrict: '請選擇地區',
      // Page 3/4
      AddDoctorAlert: '請新增至少一位醫生',
      DoctorNameEn: '醫生英文名稱',
      DoctorNameCn: '醫生中文名稱',
      Gender: '性別',
      Male: '男',
      Female: '女',
      MedicalServices: '可提供的醫療服務',
      SelectMedicalService: '請選擇醫療服務',
      RegistrationAuthority: '註冊機構',
      InsurerOptions: '保險公司選項',
      SelectBenefitCode: '保障編碼',
      Price: '已協商的醫療費用',
      DoctorList: '醫生列表',
      SaveCurrentDoctor: '保存並添加其他醫生',

      AddNewDoctor: '新增醫生',
      SelectInsurer: '選擇保險公司',
      BenefitHint: '請選擇保障類別',
      AuthorityHint: '請選擇註冊機構',
      IncorrectInsurerOptions: '請填寫正確的保險公司選項',

      // Page 4/4
      Hint: '請細閱已輸入的資料以確保資料無誤',
      Edit: '編輯',
      ConsentAlert: '請同意所有條款',
      bankAccountUserNameNotValid: '請輸入正確的銀行帳戶持有人名稱',
      phoneOrFaxNumberNotValid: '請輸入正確的電話號碼或傳真號碼',
      doctorNameNotValid: '請輸入正確的醫生名稱',
      genderNotValid: '請填寫性別',
      medicalServiceNotValid: '錯誤的醫療服務，請重新填寫',
      registrationAuthorityNotValid: '請選擇註冊機構',
      practicingCertificateNotChoose: '請選擇要上傳的執業證書',
      insurerOptionsNotValid: '保險公司選項錯誤，請重新填寫',
      RegisterSuccess: '註冊成功，請等待批核',
      RegisterFail: '註冊失敗，請聯絡客服',
      EmailRegistered: '電郵地址已被註冊',
    },

    home: {
      ST0: '驗證',
      ST1: '收費',
      ST2: '診症紀錄',
      ST3: '營業報表',
      ST4: '推廣活動',
      ST5: '最新消息',
      ST6: '診所版',
    },
    tab: {
      Home: '主頁',
      Verify: '驗證',
      Modify: '收費',
      Record: '診症紀錄',
      Setting: '設定',
    },
    verify: {
      ST0: '選擇專科',
      ST1: '選擇醫生',
      ST2: '驗證-掃描二維碼',
      ST3: '重新掃描',
      ST4: '病人資料',
      ST5: '病人編號',
      ST6: '病人支付',
      ST7: '額外藥物受保額',
      ST8: '轉介信',
      ST9: '資格',
      ST10: '通知',
      ST11: '需要',
      ST12: '不需要',
      ST13: '通過',
      ST14: '不通過',
      ST15: '輸入驗證二維碼',
      ST16: '重選醫生',
      SelectBenefit: '驗證 - 選擇專科',
      SelectDoctor: '驗證 - 選擇醫生',
      SelectVerifyMethod: '選擇驗證方法',
      Insurer: '保險公司',
      BcExample: '請輸入 1 + \"/\" + 2'
    },
    modify: {
      ST0: '支付-掃描二維碼',
      ST1: '選擇病症確認',
      ST2: '已選病症 (最多兩項)',
      ST3: '下一步',
      Back: '返回',
      ST4: '添加額外藥物',
      ST5: '支付二維碼',
      ST6: '病症',
      ST7: '服務種類',
      ST8: '額外藥物',
      ST9: '99212 - 門診服務',
      ST10: '名稱',
      ST11: '價錢',
      ST12: '添加',
      ST13: '確認收費',
      ST14: '付款資料',
      ST15: '從客戶收取',
      ST16: '診金自付額',
      ST17: '額外藥物自付額',
      ST18: '向網絡收取',
      ST19: '醫生資料',
      ST20: '醫生姓名 (號碼)',
      ST21: '診費類型',
      ST22: '病人資料',
      ST23: '輸入付費二維碼',
      ST24: '用戶編號',
      ST25: '病症',
      ST26: '服務種類',
      ST27: '額外藥物',
      ST28: '交易時間',
      ST29: '索償檔案編號',
      ST30: '搜尋病症',
      ST31: '病人姓名',
      ST32: '卡類型',
      ST33: '保單編號/\n受保人號碼',
      ST34: '交易方式',
      ST35: '總計',
      ClinicPaid: '門診自付',
      ExtraMedFee: '自付額外藥費',
      PleasePaid: '請收取病人費用',
      Signature: '簽名',
      ClearSignature: '清除簽名',
      SigndInvoice: '病人已簽署單據',
      PhysicalCard: '醫療卡',
      SelectBenefit: '付款 - 選擇專科',
      SelectDoctor: '付款 - 選擇醫生',
      WarnAtMostTwoDiagnosis: '最多只可選兩個病症',
      InvalidExtraMedFields: '不正確的額外藥物資料，或許是源於無效的字符或輸入了無效的值，包括但不限於 * | , " : < > [ ] { } ` \' ; ( ) @ & $ # % ',
      InvalidNumberOfDiagnosis: '不正確的病症數目',
      PaymentSuccess: '付款成功',
      PaymentFail: '付款失敗',
      ExtraMedTotal: '額外藥物（總額）',
      ConfirmWarning: '*本操作確認後不能編輯*',
      Submit: '確認',
      ConfirmDetails: '確認資料',
      SelectVerifyMethod: '選擇付款驗證方式',
      PatientDetail: '病人資料',
      NextPayment: '下次付款',
      TransactionComplete: '交易完成',
      DoctorName: '醫生姓名',
      ServiceType: '診所或門診病人',
      Diagnosis: '診斷'
    },
    record: {
      ST0: '診症紀錄',
      ST1: '所有紀錄',
      ST2: '已完成',
      ST3: '已退款',
      ST4: '用戶編號',
      ST5: '醫生',
      ST6: '索償檔案編號',
      ST7: '交易時間',
      ST8: '輸入操作密碼',
      ST9: '操作密碼',
      ST10: '取消',
      ST11: '確認',
      Refund: '退款',
      RefundSuccess: '退款成功',
      RefundFail: '退款失敗',
      Refunded: '已退款',
      RecordDetail: '診症紀錄詳情',
      NoRecord: '無紀錄',
      Type: '類別',
      RefundTime: '退款時間',
      PickDate: '選擇日期',
    },
    others: {
      ST0: '設定',
      ST1: '檔案',
      ST2: '關於我們',
      ST3: '條款及細則',
      ST4: '私隱政策',
      ST5: '評分',
      ST6: '分享',
      ST7: '語言設定',
      ST8: '登出',
      ST9: '區塊鏈醫療生態系統',
      ST10: '服務協議',
      ST11: '更改密碼',
      display_settings: '顯示設定',
      

      Personal_profile: '個人資料',
      Clinic_profile: '診所資料',
      Doctor_profile: '醫生資料',
      PasswordReset: '重置密碼',
      OldPassword: '確認舊密碼',
      WrongOldPassword: '舊密碼不正確',
      NewPassword: '新密碼',
      NewPasswordConfirm: '確認新密碼',
      NewPasswordNotMatch: '新密碼不吻合',
      PasswordResetSuccess: '密碼重置成功，你需要於下次登入時使用新密碼',
    },

    Settings: {
      DisplayAmountFromNetwork: '顯示「從網絡收取」',
      saveSettings: '儲存設定',
      saveSettingsSuccessfully: '成功儲存設定',
      saveSettingsFailed: '儲存設定失敗',
    },

    logout: {
      Logout_title: '登出',
      Logout_content: '你確定要登出嗎?',
    },
    profile: {
      ST0: '個人資料',
      ST1: '診所資料',
      ST2: '醫生資料',
      ST3: '公司電郵（登入電郵）',
      ST4: '密碼',
      ST5: '操作密碼',
      ST6: '聯絡人姓名',
      ST7: '聯絡電話號碼',
      ST8: '銀行戶口',
      ST9: '公司商業登記證',
      ST10: '編輯',
      ST11: '診所名稱（英文）',
      ST12: '診所名稱（中文）',
      ST13: '診所地址（英文）',
      ST14: '診所地址（中文）',
      ST15: '地區',
      ST16: '區域',
      ST17: '診所電話號碼 1',
      ST18: '診所電話號碼 2 (選填)',
      ST19: '診所傳真號碼',
      ST20: '開放時間',
      ST21: '星期一',
      ST22: '星期二',
      ST23: '星期三',
      ST24: '星期四',
      ST25: '星期五',
      ST26: '星期六',
      ST27: '星期日',
      ST28: '公眾假期',
      ST29: '休息',
      ST30: 'Doctor Name (English)',
      ST31: 'Doctor Name (Chinese)',
      ST32: 'Gender',
      ST33: 'Male',

      ST71: 'Registration Number',
      ST72: 'Title of Qualification',
      ST73: 'Name of Issuing Institution',
      ST74: 'Year of Issue',
      ST75: 'Qualifications',
      ST76: 'Speciality',
      ST77: '—',
      ST78: 'Female',
      ST88: 'Select Service',
      ST89: 'Price',
      ST90: '保險公司選',
      ST91: 'Registrant Details',
      ST92: 'Clinic Details',
      ST93: 'Doctor Details',
      ST94: 'The Medical Council of Hong Kong',
      ST95: 'Chinese Medicine Council of Hong Kong',
      ST96: 'The Dental Council of Hong Kong ',
      ST97: 'Chiropractors Council',
      ST98: 'Physiotherapists Board',
      ST99: 'Registration Authority',
      SelectInsurer: '請選擇保險公司',
    },
    authorities: {
      1: '香港醫務委員會',
      2: '香港中醫藥管理委員會',
      3: '香港牙醫管理委員會',
      4: '脊醫管理局',
      5: '物理治療師管理委員會',
    },
    medicalServices: {
      1: '普通科',
      2: '專科',
      3: '中醫藥',
      4: '物理治療',
      6: '牙科',
      7: '其它',
      9: '心臟科',
      10: '心胸肺外科',
      12: '臨床腫瘤科',
      13: '皮膚科',
      14: '內分泌及糖尿病科',
      15: '家庭醫學',
      16: '腸胃肝臟科',
      17: '外科',
      18: '血液及血液腫瘤科',
      19: '內科',
      20: '內科腫瘤科',
      21: '腎病科',
      22: '腦神經科',
      23: '婦產科',
      24: '眼科',
      25: '骨科',
      26: '耳鼻喉科',
      27: '兒科',
      28: '整形外科',
    },

    regions: {
      0: '請選擇',
      1: '香港島',
      2: '九龍',
      3: '新界',
    },
    districts: {
      3: {
        3: 'Islands',
        5: 'Kwai Tsing',
        7: 'North',
        8: 'Sai Kung',
        9: 'Sha Tin',
        12: 'Tai Po',
        13: 'Tsuen Wan',
        14: 'Tuen Mun',
        17: 'Yuen Long',
      },
      2: {
        4: 'Kowloon City',
        6: 'Kwun Tong',
        10: 'Sham Shui Po',
        16: 'Wong Tai Sin',
        18: 'Yau Tsim Mong',
      },
      1: {
        1: 'Central and Western',
        2: 'Eastern',
        11: 'Southern',
        15: 'Wan Chai',
      },
    },
    benefitCode: {
      PHY:
        'General Practitioner(PHY)/Consultation fee with 3 days prescription',
      SPL:
        'Specialist Practitioner(SPL)/ Consultation fee with 3 days prescription',
      HER: 'Chinese Herbalist(HER)/Consultation fee with 2 days prescription',
      BST: 'Bonesetter(BST)/Consultation fee with single treatment session',
      ACU: 'Acupuncture(ACU)/Consultation fee with single treatment session',
      ROE: 'Dentist(ROE)/Scaling and polishing with Oral Exam',
      PHS:
        'Physiotherapy(PHS)/Single treatment session without shockwave service',
      CHI: 'Chiropractic(CHI)/Single treatment session',
      SPO:
        'Sports/Exercise therapy(SPO)/ Consultation fee with single treatment session',
    },
    insurer: {
      BlueCross: '藍十字',
      Bowtie: '保泰人壽',
    },

    service_times: [
      '星期一',
      '星期二',
      '星期三',
      '星期四',
      '星期五',
      '星期六',
      '星期日',
      '公眾假期',
    ],

    clinic: {
      Open: '開放',
      Closed: '休息',
      AddServiceHour: '增加時間',
    },
    doctor_profile: {
      Title: '醫生資料',
      Doctor_code: '醫生編碼',
      Name_cn: '醫生名稱（中文）',
      Name_en: '醫生名稱（英文）',
      Gender: '性別',
      Service_hour: '當值時間',
      Location_code: '位置編碼',
      Doctor_fee: '已協商的醫療費用',
      Insurer_name: '保險公司名稱',
      Benefit_code: '保障編碼',
      Speciality: '可提供的醫療服務',
      Authority: '註冊機構',
      Active: '啓用',
      Inactive: '停用',
    },
    report: {
      Recent_summary: '近6個月營業概覽',
      Monthly_income_and_download: '月份營業概覽及報表下載',
      Average_client_count: '每日平均客戶數',
      Total_income: '總收入',
      Client_count: '客戶總數目',
      Download_text: '月份營業報表下載',
      ReportSent: '營業報表已發送至你的電郵，請查看你的電子郵箱/垃圾郵箱',
      ReportFail: '系統錯誤，無法發送營業報表至你的電郵地址，請聯絡客服',
      Confirm_download: '確認下載？',
      Income: '收入',
      MonthlySummary: '月份營業概覽及報表下載',
    },
    scan: {
      IncorrectCodeFormat: '錯誤的二維碼格式，請輸入其他正確的二維碼',
      InvalidCodeError: '二維碼己被使用或無法使用，請輸入其他正確的二維碼',
      UnknownCodeError: '出現未知的錯誤，請再次嘗試，或與我們的客服聯絡',
    },
    physicalCard: {
      title: '請輸入醫療卡資料 ',
      card: '醫療卡',
      policyNo: '請輸入保單編號',
      submit: '遞交',
      description: '請輸入醫療卡保單編號以作驗證',
      selected: '選中了',
      a: '請輸入保單編號',
    },
    ErrorCode: '錯誤編號',
    Confirm: '確定',
    Cancel: '取消',
    RequestCamPermission: '正在取得攝影鏡頭許可',
    Retry: '重試',
    Return: '返回',
    ST0: '登入',
    ST1: '註冊',
    ST2: '電郵',
    ST3: '密碼',
    ST4: '忘記密碼',
    ST5: '輸入',
    ST6: '確認',
    ST7: '驗證',
    ST8: '收費',
    ST9: '診症紀錄',
    ST10: '營業報表',
    ST11: '推廣活動',
    ST12: '最新消息',
    ST13: '選擇專科',
    ST14: '選擇醫生',
    ST15: '掃描驗證碼',
    ST16: '重新掃描',
    ST17: '用戶資料',
    ST18: '用戶編號',
    ST19: '自付額',
    ST20: '額外藥物保額額度',
    ST21: '轉介信',
    ST22: '資格檢查',
    ST23: '注意事項',
    ST24: '需要',
    ST25: '不需要',
    ST26: '通過',
    ST27: '不通過',
    ST28: '掃描付款二維碼',
    ST29: '1/2 - 病症確認',
    ST30: '已選病症',
    ST31: '下一步',
    ST32: '2/2 - 病症確認',
    ST33: '付款二維碼',
    ST34: '病症',
    ST35: '服務種類',
    ST36: '額外藥物',
    ST37: '99212 - 門診服務',
    ST38: '名稱',
    ST39: '價錢',
    ST40: '添加',
    ST41: '確認收費',
    ST42: '付款資料',
    ST43: '請向客人收取',
    ST44: '自付額',
    ST45: '額外藥費',
    ST46: '向網絡收取',
    ST47: 'Doctor Details',
    ST48: 'Doctor Name',
    ST49: 'Type of Consultation',
    ST50: '病人資料',
    ST51: '請輸入正確的電郵地址',
    ST52: '推廣詳情',
    ST53: '消息',
    ST54: '二維碼',
    ST55: '醫療卡',
    IncorrectOPPassword: '錯誤的操作密碼',
    Next: '下一步',
    Save: '儲存',
    Close: '關閉',
    UnknownSystemError: '發生未知的系統錯誤，請稍後再重試，或聯絡客服',
    tick1_Text00: '我已閱讀並同意醫結的',
    tick1_Text01: '「使用條款及免責聲明」',

    tick2_Text00: '我已閱讀及同意醫結最新版的',
    tick2_Text01: '服務協議',

    tick3_Text00: '我已閱讀並明白，醫結的',
    tick3_Text01: '「收集個人資料聲明」，',
    tick3_Text02: '並確認根據收集個人資料聲明接收本公司推廣之訊息或資料。',
    trust_parter: '我們的合作夥伴',
  },
};

export default Strings;
